import pageURL from '@/core/config/pageURL';

export const CHUONG_TRINH_RESOURCE_KEYS = {
  NGANH: 'nganh',
  TRINH_DO_DAO_TAO: 'trinh-do-dao-tao',
  LOAI_CHUONG_TRINH: 'loai-chuong-trinh',
  KHUNG_KY: 'khung-ky',
  CHUONG_TRINH: 'chuong-trinh',
  CHUONG_TRINH_VERSION: 'chuong-trinh-version',
  CHUONG_TRINH_MON: 'chuong-trinh-mon',
  MON_HOC: 'mon-hoc',
  DIEU_KIEN_MON_HOC: 'dieu-kien-mon-hoc',
  DIEU_KIEN_TOT_NGHIEP: 'dieu-kien-tot-nghiep',
  MON_TIEN_QUYET: 'mon-tien-quyet',
  MON_TU_CHON: 'mon-tu-chon',
  MUC_TIEU_CHUONG_TRINH: 'muc-tieu-chuong-trinh',
  NANG_LUC_DAU_RA: 'nang-luc-dau-ra',
  NHOM_KIEN_THUC: 'nhom-kien-thuc',
  NHOM_TU_CHON: 'nhom-tu-chon',
  QUY_DOI_DIEM: 'quy-doi-diem',
  SYLLABUS_CHUONG_BAI: 'syllabus-chuong-bai',
  SYLLABUS_CHUONG_TRINH: 'syllabus-chuong-trinh',
  SYLLABUS_MON_HOC: 'syllabus-mon-hoc',
  SYLLABUS_TAI_LIEU: 'syllabus-tai-lieu',
  VI_TRI_VIEC_LAM: 'vi-tri-viec-lam',
};

const column = (key, label, options = {}) => ({ key, label, ...options });
const field = (key, label, type = 'text', options = {}) => ({ key, label, type, ...options });
const numberField = (key, label, options = {}) => field(key, label, 'number', options);
const dateField = (key, label, options = {}) => field(key, label, 'date', options);
const checkField = (key, label, options = {}) => field(key, label, 'checkbox', options);
const textArea = (key, label, options = {}) => field(key, label, 'textarea', { wide: true, ...options });

export const CHUONG_TRINH_RESOURCES = [

  {
    key: CHUONG_TRINH_RESOURCE_KEYS.NGANH,
    segment: 'nganh',
    title: 'Ngành',
    description: 'Quản lý danh mục ngành đào tạo dùng khi lập chương trình.',
    endpoint: pageURL.daoTao.NGANH,
    idKey: 'id',
    searchFields: ['maNganh', 'tenNganh', 'moTa'],
    columns: [column('id', 'ID', { width: '70px' }), column('maNganh', 'Mã ngành', { width: '130px' }), column('tenNganh', 'Tên ngành', { minWidth: '240px' }), column('moTa', 'Mô tả', { minWidth: '260px' })],
    fields: [field('maNganh', 'Mã ngành', 'text', { required: true }), field('tenNganh', 'Tên ngành', 'text', { required: true, wide: true }), textArea('moTa', 'Mô tả')],
    filters: [],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.TRINH_DO_DAO_TAO,
    segment: 'trinh-do-dao-tao',
    title: 'Trình độ',
    description: 'Quản lý trình độ đào tạo áp dụng cho chương trình.',
    endpoint: pageURL.daoTao.TRINH_DO_DAO_TAO,
    idKey: 'id',
    searchFields: ['maTrinhDo', 'tenTrinhDo', 'moTa'],
    columns: [column('id', 'ID', { width: '70px' }), column('maTrinhDo', 'Mã trình độ', { width: '140px' }), column('tenTrinhDo', 'Tên trình độ', { minWidth: '240px' }), column('moTa', 'Mô tả', { minWidth: '260px' })],
    fields: [field('maTrinhDo', 'Mã trình độ', 'text', { required: true }), field('tenTrinhDo', 'Tên trình độ', 'text', { required: true, wide: true }), textArea('moTa', 'Mô tả')],
    filters: [],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.LOAI_CHUONG_TRINH,
    segment: 'loai-chuong-trinh',
    title: 'Loại chương trình',
    description: 'Quản lý loại chương trình, số tháng và số kỳ đào tạo.',
    endpoint: pageURL.daoTao.LOAI_CHUONG_TRINH,
    idKey: 'id',
    searchFields: ['maLoai', 'tenLoai', 'moTa'],
    columns: [column('id', 'ID', { width: '70px' }), column('maLoai', 'Mã loại', { width: '130px' }), column('tenLoai', 'Tên loại', { minWidth: '220px' }), column('soThang', 'Số tháng', { width: '100px', align: 'right' }), column('soKy', 'Số kỳ', { width: '90px', align: 'right' })],
    fields: [field('maLoai', 'Mã loại', 'text', { required: true }), field('tenLoai', 'Tên loại', 'text', { required: true, wide: true }), numberField('soThang', 'Số tháng', { required: true }), numberField('soKy', 'Số kỳ', { required: true }), textArea('moTa', 'Mô tả')],
    filters: [],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.KHUNG_KY,
    segment: 'khung-ky',
    title: 'Khung kỳ',
    description: 'Quản lý kỳ học theo loại chương trình để sắp xếp môn.',
    endpoint: pageURL.daoTao.KHUNG_KY,
    idKey: 'id',
    searchFields: ['maKy', 'tenKy'],
    columns: [column('id', 'ID', { width: '70px' }), column('loaiChuongTrinhId', 'Loại CT ID', { width: '120px', align: 'right' }), column('maKy', 'Mã kỳ', { width: '120px' }), column('tenKy', 'Tên kỳ', { minWidth: '220px' }), column('thuTu', 'Thứ tự', { width: '90px', align: 'right' })],
    fields: [numberField('loaiChuongTrinhId', 'Loại chương trình ID', { required: true }), field('maKy', 'Mã kỳ', 'text', { required: true }), field('tenKy', 'Tên kỳ', 'text', { required: true, wide: true }), numberField('thuTu', 'Thứ tự', { required: true })],
    filters: [numberField('loaiChuongTrinhId', 'Loại CT ID')],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.CHUONG_TRINH,
    segment: 'chuong-trinh',
    title: 'Chương trình đào tạo',
    description: 'Quản lý chương trình theo ngành, trình độ và loại chương trình.',
    endpoint: pageURL.chuongTrinh.CHUONG_TRINH,
    idKey: 'id',
    searchFields: ['maChuongTrinh', 'tenChuongTrinh', 'doiTuongTuyenSinh', 'thoiGianDaoTao'],
    columns: [
      column('id', 'ID', { width: '70px' }),
      column('maChuongTrinh', 'Mã CT', { width: '130px' }),
      column('tenChuongTrinh', 'Tên chương trình', { minWidth: '240px' }),
      column('nganhId', 'Ngành ID', { width: '100px', align: 'right' }),
      column('trinhDoId', 'Trình độ ID', { width: '110px', align: 'right' }),
      column('loaiChuongTrinhId', 'Loại CT ID', { width: '115px', align: 'right' }),
      column('thoiGianDaoTao', 'Thời gian', { width: '120px' }),
    ],
    fields: [
      numberField('nganhId', 'Ngành ID', { required: true }),
      numberField('trinhDoId', 'Trình độ ID', { required: true }),
      numberField('loaiChuongTrinhId', 'Loại chương trình ID', { required: true }),
      field('maChuongTrinh', 'Mã chương trình', 'text', { required: true }),
      field('tenChuongTrinh', 'Tên chương trình', 'text', { required: true, wide: true }),
      field('thoiGianDaoTao', 'Thời gian đào tạo'),
      textArea('doiTuongTuyenSinh', 'Đối tượng tuyển sinh'),
    ],
    filters: [numberField('nganhId', 'Ngành ID'), numberField('trinhDoId', 'Trình độ ID'), numberField('loaiChuongTrinhId', 'Loại CT ID')],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.CHUONG_TRINH_VERSION,
    segment: 'chuong-trinh-version',
    title: 'Phiên bản chương trình',
    description: 'Quản lý version, quyết định, tổng tín chỉ và hiệu lực chương trình.',
    endpoint: pageURL.chuongTrinh.CHUONG_TRINH_VERSION,
    idKey: 'id',
    searchFields: ['maVersion', 'tenVersion', 'soQuyetDinh', 'nguoiKy', 'coQuanBanHanh'],
    columns: [
      column('id', 'ID', { width: '70px' }),
      column('maVersion', 'Mã version', { width: '130px' }),
      column('tenVersion', 'Tên version', { minWidth: '230px' }),
      column('chuongTrinhId', 'CT ID', { width: '90px', align: 'right' }),
      column('ngayApDung', 'Áp dụng', { type: 'date', width: '115px' }),
      column('tongTinChi', 'Tín chỉ', { width: '90px', align: 'right' }),
      column('laHienHanh', 'Hiện hành', { type: 'boolean', width: '100px' }),
    ],
    fields: [
      numberField('chuongTrinhId', 'Chương trình ID', { required: true }),
      field('maVersion', 'Mã version', 'text', { required: true }),
      field('tenVersion', 'Tên version', 'text', { wide: true }),
      dateField('ngayApDung', 'Ngày áp dụng'),
      dateField('ngayHetHieuLuc', 'Ngày hết hiệu lực'),
      field('soQuyetDinh', 'Số quyết định'),
      dateField('ngayQuyetDinh', 'Ngày quyết định'),
      field('nguoiKy', 'Người ký'),
      field('coQuanBanHanh', 'Cơ quan ban hành'),
      field('fileQuyetDinh', 'File quyết định', 'text', { wide: true }),
      numberField('tongTinChi', 'Tổng tín chỉ'),
      numberField('tongSoGio', 'Tổng số giờ'),
      numberField('tongGioLyThuyet', 'Giờ lý thuyết'),
      numberField('tongGioThucHanh', 'Giờ thực hành'),
      numberField('tongGioKiemTra', 'Giờ kiểm tra'),
      checkField('laHienHanh', 'Là hiện hành'),
    ],
    filters: [numberField('chuongTrinhId', 'Chương trình ID')],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.MON_HOC,
    segment: 'mon-hoc',
    title: 'Môn học',
    description: 'Quản lý danh mục môn học dùng trong chương trình đào tạo.',
    endpoint: pageURL.chuongTrinh.MON_HOC,
    idKey: 'id',
    searchFields: ['maMon', 'tenMon', 'moTa'],
    columns: [column('id', 'ID', { width: '70px' }), column('maMon', 'Mã môn', { width: '130px' }), column('tenMon', 'Tên môn học', { minWidth: '260px' }), column('moTa', 'Mô tả', { minWidth: '260px' })],
    fields: [field('maMon', 'Mã môn', 'text', { required: true }), field('tenMon', 'Tên môn học', 'text', { required: true, wide: true }), textArea('moTa', 'Mô tả')],
    filters: [],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.CHUONG_TRINH_MON,
    segment: 'chuong-trinh-mon',
    title: 'Môn trong chương trình',
    description: 'Gắn môn học vào version chương trình, kỳ học và nhóm kiến thức.',
    endpoint: pageURL.chuongTrinh.CHUONG_TRINH_MON,
    idKey: 'id',
    searchFields: ['maMonTrongCt', 'loai', 'loaiHocPhan', 'ghiChu'],
    columns: [
      column('id', 'ID', { width: '70px' }), column('maMonTrongCt', 'Mã môn CT', { width: '130px' }), column('chuongTrinhVersionId', 'Version ID', { width: '110px', align: 'right' }), column('monHocId', 'Môn ID', { width: '90px', align: 'right' }), column('soTinChi', 'TC', { width: '80px', align: 'right' }), column('tongGio', 'Giờ', { width: '80px', align: 'right' }), column('batBuoc', 'Bắt buộc', { type: 'boolean', width: '100px' }),
    ],
    fields: [
      numberField('chuongTrinhVersionId', 'Version ID', { required: true }), numberField('monHocId', 'Môn học ID', { required: true }), field('maMonTrongCt', 'Mã môn trong CT', 'text', { required: true }), numberField('khungKyId', 'Khung kỳ ID'), numberField('nhomKienThucId', 'Nhóm kiến thức ID'), field('loai', 'Loại'), field('loaiHocPhan', 'Loại học phần'), checkField('batBuoc', 'Bắt buộc'), checkField('laMonDieuKien', 'Là môn điều kiện'), numberField('thuTu', 'Thứ tự'), numberField('soTinChi', 'Số tín chỉ'), numberField('tongGio', 'Tổng giờ'), numberField('gioLyThuyet', 'Giờ lý thuyết'), numberField('gioThucHanh', 'Giờ thực hành'), numberField('gioKiemTra', 'Giờ kiểm tra'), textArea('ghiChu', 'Ghi chú'),
    ],
    filters: [numberField('chuongTrinhVersionId', 'Version ID'), numberField('monHocId', 'Môn học ID')],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.NHOM_KIEN_THUC,
    segment: 'nhom-kien-thuc',
    title: 'Nhóm kiến thức',
    description: 'Quản lý nhóm kiến thức trong version chương trình.',
    endpoint: pageURL.chuongTrinh.NHOM_KIEN_THUC,
    idKey: 'id',
    searchFields: ['ma', 'ten', 'loaiNhom'],
    columns: [column('id', 'ID', { width: '70px' }), column('ma', 'Mã', { width: '110px' }), column('ten', 'Tên nhóm', { minWidth: '220px' }), column('chuongTrinhVersionId', 'Version ID', { width: '110px', align: 'right' }), column('loaiNhom', 'Loại nhóm', { width: '130px' }), column('tongTinChi', 'Tín chỉ', { width: '90px', align: 'right' })],
    fields: [numberField('chuongTrinhVersionId', 'Version ID', { required: true }), field('ma', 'Mã', 'text', { required: true }), field('ten', 'Tên nhóm', 'text', { required: true, wide: true }), numberField('thuTu', 'Thứ tự'), field('loaiNhom', 'Loại nhóm'), numberField('tongTinChi', 'Tổng tín chỉ'), numberField('tongSoGio', 'Tổng số giờ'), numberField('tongGioLyThuyet', 'Giờ lý thuyết'), numberField('tongGioThucHanh', 'Giờ thực hành'), numberField('tongGioKiemTra', 'Giờ kiểm tra')],
    filters: [numberField('chuongTrinhVersionId', 'Version ID')],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.MUC_TIEU_CHUONG_TRINH,
    segment: 'muc-tieu-chuong-trinh',
    title: 'Mục tiêu chương trình',
    description: 'Quản lý mục tiêu đào tạo theo version chương trình.',
    endpoint: pageURL.chuongTrinh.MUC_TIEU_CHUONG_TRINH,
    idKey: 'id',
    searchFields: ['loai', 'noiDung'],
    columns: [column('id', 'ID', { width: '70px' }), column('chuongTrinhVersionId', 'Version ID', { width: '110px', align: 'right' }), column('loai', 'Loại', { width: '130px' }), column('noiDung', 'Nội dung', { minWidth: '320px' }), column('thuTu', 'Thứ tự', { width: '90px', align: 'right' })],
    fields: [numberField('chuongTrinhVersionId', 'Version ID', { required: true }), field('loai', 'Loại'), textArea('noiDung', 'Nội dung', { required: true }), numberField('thuTu', 'Thứ tự')],
    filters: [numberField('chuongTrinhVersionId', 'Version ID')],
  },
  {
    key: CHUONG_TRINH_RESOURCE_KEYS.NANG_LUC_DAU_RA,
    segment: 'nang-luc-dau-ra',
    title: 'Năng lực đầu ra',
    description: 'Quản lý chuẩn đầu ra theo chương trình.',
    endpoint: pageURL.chuongTrinh.NANG_LUC_DAU_RA,
    idKey: 'id',
    searchFields: ['ma', 'noiDung', 'loai'],
    columns: [column('id', 'ID', { width: '70px' }), column('ma', 'Mã', { width: '110px' }), column('noiDung', 'Nội dung', { minWidth: '320px' }), column('loai', 'Loại', { width: '130px' }), column('thuTu', 'Thứ tự', { width: '90px', align: 'right' })],
    fields: [numberField('chuongTrinhVersionId', 'Version ID', { required: true }), field('ma', 'Mã', 'text', { required: true }), textArea('noiDung', 'Nội dung', { required: true }), field('loai', 'Loại'), numberField('thuTu', 'Thứ tự')],
    filters: [numberField('chuongTrinhVersionId', 'Version ID')],
  },
  ...[
    ['dieu-kien-mon-hoc', 'Điều kiện môn học', pageURL.chuongTrinh.DIEU_KIEN_MON_HOC, [numberField('syllabusMonId', 'Syllabus môn ID', { required: true }), field('loai', 'Loại'), textArea('noiDung', 'Nội dung'), numberField('thuTu', 'Thứ tự')], ['syllabusMonId', 'loai', 'noiDung']],
    ['dieu-kien-tot-nghiep', 'Điều kiện tốt nghiệp', pageURL.chuongTrinh.DIEU_KIEN_TOT_NGHIEP, [numberField('chuongTrinhVersionId', 'Version ID', { required: true }), textArea('noiDung', 'Nội dung'), numberField('thuTu', 'Thứ tự')], ['chuongTrinhVersionId', 'noiDung']],
    ['mon-tien-quyet', 'Môn tiên quyết', pageURL.chuongTrinh.MON_TIEN_QUYET, [numberField('monId', 'Môn ID', { required: true }), numberField('monDieuKienId', 'Môn điều kiện ID', { required: true }), field('loai', 'Loại'), textArea('ghiChu', 'Ghi chú')], ['monId', 'monDieuKienId', 'loai', 'ghiChu']],
    ['mon-tu-chon', 'Môn tự chọn', pageURL.chuongTrinh.MON_TU_CHON, [numberField('nhomId', 'Nhóm ID', { required: true }), numberField('chuongTrinhMonId', 'Môn CT ID', { required: true })], ['nhomId', 'chuongTrinhMonId']],
    ['nhom-tu-chon', 'Nhóm tự chọn', pageURL.chuongTrinh.NHOM_TU_CHON, [numberField('chuongTrinhVersionId', 'Version ID', { required: true }), field('ten', 'Tên nhóm', 'text', { required: true, wide: true }), numberField('soMonChon', 'Số môn chọn'), numberField('soTinChiCanDat', 'Số tín chỉ cần đạt'), textArea('ghiChu', 'Ghi chú')], ['chuongTrinhVersionId', 'ten', 'ghiChu']],
    ['quy-doi-diem', 'Quy đổi điểm', pageURL.chuongTrinh.QUY_DOI_DIEM, [numberField('chuongTrinhMonId', 'Môn CT ID', { required: true }), numberField('nguongTu', 'Ngưỡng từ'), numberField('nguongDen', 'Ngưỡng đến'), numberField('diemQuyDoi', 'Điểm quy đổi'), field('ketQua', 'Kết quả'), field('congThuc', 'Công thức'), textArea('ghiChu', 'Ghi chú')], ['chuongTrinhMonId', 'ketQua', 'congThuc']],
    ['syllabus-chuong-bai', 'Syllabus chương bài', pageURL.chuongTrinh.SYLLABUS_CHUONG_BAI, [numberField('syllabusMonId', 'Syllabus môn ID', { required: true }), field('ten', 'Tên chương/bài', 'text', { required: true, wide: true }), numberField('tongGio', 'Tổng giờ'), numberField('gioLyThuyet', 'Giờ lý thuyết'), numberField('gioThucHanh', 'Giờ thực hành'), numberField('gioKiemTra', 'Giờ kiểm tra'), textArea('noiDung', 'Nội dung'), textArea('mucTieu', 'Mục tiêu'), numberField('thuTu', 'Thứ tự')], ['syllabusMonId', 'ten', 'noiDung']],
    ['syllabus-chuong-trinh', 'Syllabus chương trình', pageURL.chuongTrinh.SYLLABUS_CHUONG_TRINH, [numberField('chuongTrinhVersionId', 'Version ID', { required: true }), textArea('moTaTongQuan', 'Mô tả tổng quan'), textArea('mucDich', 'Mục đích'), textArea('yeuCauDaoTao', 'Yêu cầu đào tạo'), textArea('phuongPhapDaoTao', 'Phương pháp đào tạo'), textArea('ghiChu', 'Ghi chú')], ['chuongTrinhVersionId', 'moTaTongQuan', 'mucDich']],
    ['syllabus-mon-hoc', 'Syllabus môn học', pageURL.chuongTrinh.SYLLABUS_MON_HOC, [numberField('chuongTrinhMonId', 'Môn CT ID', { required: true }), field('viTri', 'Vị trí'), field('tinhChat', 'Tính chất'), textArea('mucTieu', 'Mục tiêu'), textArea('phuongPhapDanhGia', 'Phương pháp đánh giá'), textArea('dieuKienHoanThanh', 'Điều kiện hoàn thành'), textArea('huongDan', 'Hướng dẫn'), numberField('diemDatToiThieu', 'Điểm đạt tối thiểu'), field('donViDiem', 'Đơn vị điểm'), numberField('tyLeChuyenCanToiThieu', 'Tỷ lệ chuyên cần tối thiểu'), checkField('batBuocDuThi', 'Bắt buộc dự thi'), field('congThucQuyDoi', 'Công thức quy đổi', 'text', { wide: true })], ['chuongTrinhMonId', 'viTri', 'mucTieu']],
    ['syllabus-tai-lieu', 'Syllabus tài liệu', pageURL.chuongTrinh.SYLLABUS_TAI_LIEU, [numberField('syllabusMonId', 'Syllabus môn ID', { required: true }), field('ten', 'Tên tài liệu', 'text', { required: true, wide: true }), field('tacGia', 'Tác giả'), numberField('namXuatBan', 'Năm xuất bản'), field('nhaXuatBan', 'Nhà xuất bản'), field('loai', 'Loại'), textArea('ghiChu', 'Ghi chú')], ['syllabusMonId', 'ten', 'tacGia']],
    ['vi-tri-viec-lam', 'Vị trí việc làm', pageURL.chuongTrinh.VI_TRI_VIEC_LAM, [numberField('chuongTrinhVersionId', 'Version ID', { required: true }), field('ten', 'Tên vị trí', 'text', { required: true, wide: true }), textArea('moTa', 'Mô tả'), numberField('thuTu', 'Thứ tự')], ['chuongTrinhVersionId', 'ten', 'moTa']],
  ].map(([segment, title, endpoint, fields, searchFields]) => ({
    key: segment,
    segment,
    title,
    description: `Quản lý dữ liệu ${title.toLowerCase()} theo controller backend.`,
    endpoint,
    idKey: 'id',
    searchFields,
    columns: [
      column('id', 'ID', { width: '70px' }),
      ...fields.slice(0, 5).map((item) => column(item.key, item.label, { minWidth: item.type === 'textarea' ? '260px' : undefined, width: item.type === 'number' ? '110px' : undefined, align: item.type === 'number' ? 'right' : undefined })),
    ],
    fields,
    filters: fields.filter((item) => item.key.endsWith('Id')).slice(0, 2),
  })),
];

export const CHUONG_TRINH_RESOURCE_MAP = CHUONG_TRINH_RESOURCES.reduce((map, item) => {
  map[item.key] = item;
  return map;
}, {});

export const DEFAULT_CHUONG_TRINH_RESOURCE = CHUONG_TRINH_RESOURCES[0];
