export * from './ChuongTrinhController.js';
export * from './ChuongTrinhMonController.js';
export * from './ChuongTrinhVersionController.js';
export * from './DieuKienMonHocController.js';
export * from './DieuKienTotNghiepController.js';
export * from './MonHocController.js';
export * from './MonTienQuyetController.js';
// export * from './MonTuChonController';
export * from './MucTieuChuongTrinhController.js';
export * from './NangLucDauRaController.js';
export * from './NhomKienThucController.js';
export * from './NhomTuChonController.js';
export * from './QuyDoiDiemController.js';
export * from './SyllabusChuongBaiController.js';
export * from './SyllabusChuongTrinhController.js';
export * from './SyllabusMonHocController.js';
export * from './SyllabusTaiLieuController.js';
export * from './ViTriViecLamController.js';
