<template>
  <section class="ct-screen"><div class="ct-shell">
    <header class="ct-page-head"><div class="ct-head-main"><div class="ct-kicker">Môn học trong chương trình</div><h1 class="ct-title">{{ title }}</h1><p class="ct-desc">Quản lý đề cương, chương bài, tài liệu, điều kiện và quy đổi điểm của môn học.</p></div><div class="ct-actions"><RouterLink class="ct-btn light" :to="`/quy-trinh/chuong-trinh/${chuongTrinhId}/phien-ban/${versionId}/khung`">Quay về</RouterLink><button class="ct-btn light" type="button" @click="openEditMon">Sửa môn</button><button class="ct-btn" type="button" @click="openCreateRelated">Thêm dữ liệu</button></div></header>
    <main class="ct-main"><section class="ct-info-grid"><article class="ct-info"><b>Mã môn CT</b><span>{{ detail.maMonTrongCt || '—' }}</span></article><article class="ct-info"><b>Tín chỉ</b><span>{{ detail.soTinChi || '—' }}</span></article><article class="ct-info"><b>Tổng giờ</b><span>{{ detail.tongGio || '—' }}</span></article><article class="ct-info"><b>Tính chất</b><span>{{ detail.batBuoc ? 'Bắt buộc' : 'Tự chọn' }}</span></article></section>
      <section class="ct-panel"><div class="ct-tabs"><button v-for="tab in tabs" :key="tab.key" :class="['ct-tab',{active:activeTab===tab.key}]" type="button" @click="activeTab=tab.key">{{ tab.label }}</button></div><div class="ct-panel-head"><div><h2 class="ct-panel-title">{{ currentTitle }}</h2><p class="ct-panel-subtitle">{{ currentRows.length }} bản ghi</p></div><button class="ct-btn" type="button" @click="openCreateRelated">Thêm mới</button></div><div v-if="loading" class="ct-loading">Đang tải chi tiết môn học...</div><div v-else-if="error" class="ct-error">{{ error }}</div><div v-else class="ct-list"><article v-for="item in currentRows" :key="layIdBanGhi(item)" class="ct-list-item"><b>{{ labelRelated(item) }}</b><div class="ct-muted">{{ item.noiDung || item.mucTieu || item.moTa || item.ghiChu || item.tacGia || '—' }}</div><div class="ct-actions" style="margin-top:10px"><button class="ct-btn small light" type="button" @click="openEditRelated(item)">Sửa</button><button class="ct-btn small danger" type="button" @click="removeRelated(item)">Xóa</button></div></article><div v-if="!currentRows.length" class="ct-empty">Chưa có dữ liệu.</div></div></section>
    </main></div>
    <BieuMauQuanLyModal v-model="monForm" :open="monModal" mode="edit" :fields="monFields" :saving="saving" title="Môn trong chương trình" @close="monModal=false" @submit="saveMon" />
    <BieuMauQuanLyModal v-model="relatedForm" :open="relatedModal" :mode="relatedMode" :fields="currentFields" :saving="saving" :title="currentTitle" @close="relatedModal=false" @submit="saveRelated" />
  </section>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue';import { useRoute } from 'vue-router';import './luongChuongTrinh.css';import BieuMauQuanLyModal from '@/modules/chuongTrinh/components/modal/BieuMauQuanLyModal.vue';import { CHUONG_TRINH_RESOURCE_MAP } from '@/modules/chuongTrinh/constants/trangThaiChuongTrinh.js';import { API_LUONG_CHUONG_TRINH, capNhatBanGhi, layChiTietMonTrongChuongTrinh, layDanhSachDieuKienMonHoc, layDanhSachMonTienQuyet, layDanhSachQuyDoiDiem, layDanhSachSyllabusChuongBai, layDanhSachSyllabusMonHoc, layDanhSachSyllabusTaiLieu, layIdBanGhi, locTheoGiaTri, taoBanGhi, taoNhanMonHoc, xoaBanGhi } from '@/modules/chuongTrinh/services/luongChuongTrinhDaoTaoService.js';
const route=useRoute();const chuongTrinhId=computed(()=>route.params.chuongTrinhId);const versionId=computed(()=>route.params.versionId);const chuongTrinhMonId=computed(()=>route.params.chuongTrinhMonId);const detail=ref({});const loading=ref(false);const saving=ref(false);const error=ref('');const activeTab=ref('syllabus');const title=computed(()=>taoNhanMonHoc(detail.value));const rows=ref({syllabus:[],chuongBai:[],taiLieu:[],dieuKien:[],tienQuyet:[],quyDoi:[]});
const tabs=[{key:'syllabus',label:'Đề cương',resource:'syllabus-mon-hoc',endpoint:API_LUONG_CHUONG_TRINH.SYLLABUS_MON_HOC,parentKey:'chuongTrinhMonId'},{key:'chuongBai',label:'Chương bài',resource:'syllabus-chuong-bai',endpoint:API_LUONG_CHUONG_TRINH.SYLLABUS_CHUONG_BAI,parentKey:'syllabusMonId'},{key:'taiLieu',label:'Tài liệu',resource:'syllabus-tai-lieu',endpoint:API_LUONG_CHUONG_TRINH.SYLLABUS_TAI_LIEU,parentKey:'syllabusMonId'},{key:'dieuKien',label:'Điều kiện',resource:'dieu-kien-mon-hoc',endpoint:API_LUONG_CHUONG_TRINH.DIEU_KIEN_MON_HOC,parentKey:'syllabusMonId'},{key:'tienQuyet',label:'Tiên quyết',resource:'mon-tien-quyet',endpoint:API_LUONG_CHUONG_TRINH.MON_TIEN_QUYET,parentKey:'monId'},{key:'quyDoi',label:'Quy đổi điểm',resource:'quy-doi-diem',endpoint:API_LUONG_CHUONG_TRINH.QUY_DOI_DIEM,parentKey:'chuongTrinhMonId'}];
const currentTab=computed(()=>tabs.find(t=>t.key===activeTab.value)||tabs[0]);const currentTitle=computed(()=>CHUONG_TRINH_RESOURCE_MAP[currentTab.value.resource]?.title||currentTab.value.label);const currentFields=computed(()=>CHUONG_TRINH_RESOURCE_MAP[currentTab.value.resource]?.fields||[]);const currentRows=computed(()=>rows.value[activeTab.value]||[]);const monFields=CHUONG_TRINH_RESOURCE_MAP['chuong-trinh-mon'].fields;const monModal=ref(false);const relatedModal=ref(false);const relatedMode=ref('create');const monForm=ref({});const relatedForm=ref({});const syllabusId=computed(()=>layIdBanGhi(rows.value.syllabus?.[0])||'');
const labelRelated=(item)=>item.ten||item.tenChuong||item.tenTaiLieu||item.viTri||item.loai||item.ketQua||item.ma||`#${layIdBanGhi(item)}`;
const loadData=async()=>{loading.value=true;error.value='';try{const [ctm,sy,cb,tl,dk,tq,qd]=await Promise.all([layChiTietMonTrongChuongTrinh(chuongTrinhMonId.value),layDanhSachSyllabusMonHoc({chuongTrinhMonId:chuongTrinhMonId.value}),layDanhSachSyllabusChuongBai(),layDanhSachSyllabusTaiLieu(),layDanhSachDieuKienMonHoc(),layDanhSachMonTienQuyet({monId:chuongTrinhMonId.value}),layDanhSachQuyDoiDiem({chuongTrinhMonId:chuongTrinhMonId.value})]);detail.value=ctm||{};const syRows=locTheoGiaTri(sy,'chuongTrinhMonId',chuongTrinhMonId.value);const syId=layIdBanGhi(syRows[0]);rows.value={syllabus:syRows,chuongBai:syId?locTheoGiaTri(cb,'syllabusMonId',syId):[],taiLieu:syId?locTheoGiaTri(tl,'syllabusMonId',syId):[],dieuKien:syId?locTheoGiaTri(dk,'syllabusMonId',syId):[],tienQuyet:tq,quyDoi:locTheoGiaTri(qd,'chuongTrinhMonId',chuongTrinhMonId.value)};}catch(err){error.value=err?.message||'Không tải được chi tiết môn học.';}finally{loading.value=false;}};
const openEditMon=()=>{monForm.value={...detail.value};monModal.value=true;};const saveMon=async()=>{saving.value=true;try{await capNhatBanGhi(API_LUONG_CHUONG_TRINH.MON_TRONG_CHUONG_TRINH,chuongTrinhMonId.value,monForm.value);monModal.value=false;await loadData();}finally{saving.value=false;}};
const openCreateRelated=()=>{relatedMode.value='create';const parentKey=currentTab.value.parentKey;const parentValue=parentKey==='syllabusMonId'?syllabusId.value:chuongTrinhMonId.value;relatedForm.value={[parentKey]:Number(parentValue)||parentValue};relatedModal.value=true;};const openEditRelated=(item)=>{relatedMode.value='edit';relatedForm.value={...item};relatedModal.value=true;};
const saveRelated=async()=>{saving.value=true;try{const id=layIdBanGhi(relatedForm.value);if(relatedMode.value==='edit'&&id)await capNhatBanGhi(currentTab.value.endpoint,id,relatedForm.value);else await taoBanGhi(currentTab.value.endpoint,relatedForm.value);relatedModal.value=false;await loadData();}finally{saving.value=false;}};const removeRelated=async(item)=>{const id=layIdBanGhi(item);if(id&&confirm('Xóa bản ghi này?')){await xoaBanGhi(currentTab.value.endpoint,id);await loadData();}};
onMounted(loadData);
</script>
