<template>
  <section class="ct-screen"><div class="ct-shell">
    <header class="ct-page-head"><div class="ct-head-main"><div class="ct-kicker">Khung chương trình</div><h1 class="ct-title">Nhóm kiến thức và môn học</h1><p class="ct-desc">Quản lý nhóm kiến thức và môn học theo đúng phiên bản chương trình.</p></div><div class="ct-actions"><RouterLink class="ct-btn light" :to="`/quy-trinh/chuong-trinh/${chuongTrinhId}/phien-ban/${versionId}`">Quay về phiên bản</RouterLink></div></header>
    <main class="ct-main"><section class="ct-stat-grid"><article class="ct-stat"><b>Nhóm kiến thức</b><strong>{{ nhomRows.length }}</strong><span>Trong version</span></article><article class="ct-stat"><b>Môn học</b><strong>{{ monRows.length }}</strong><span>Trong khung</span></article><article class="ct-stat"><b>Đang hiển thị</b><strong>{{ monRowsLoc.length }}</strong><span>Theo nhóm chọn</span></article><article class="ct-stat"><b>Tổng tín chỉ</b><strong>{{ tongTinChi }}</strong><span>Từ môn học</span></article></section>
      <section class="ct-khung-grid"><aside class="ct-panel"><div class="ct-panel-head"><div><h2 class="ct-panel-title">Nhóm kiến thức</h2><p class="ct-panel-subtitle">Chọn nhóm để lọc môn.</p></div><button class="ct-btn small light" type="button" @click="openCreateNhom">Thêm nhóm</button></div><div class="ct-group-list"><button :class="['ct-group-btn',{active:!activeNhomId}]" type="button" @click="activeNhomId=''"><b>Tất cả nhóm</b><span>{{ monRows.length }} môn</span></button><button v-for="nhom in nhomRows" :key="layIdBanGhi(nhom)" :class="['ct-group-btn',{active:String(activeNhomId)===String(layIdBanGhi(nhom))}]" type="button" @click="activeNhomId=layIdBanGhi(nhom)"><b>{{ nhom.ten || nhom.tenNhom || nhom.ma || 'Nhóm kiến thức' }}</b><span>{{ demMonTheoNhom(layIdBanGhi(nhom)) }} môn</span></button></div></aside>
        <section class="ct-panel"><div class="ct-panel-head"><div><h2 class="ct-panel-title">Môn trong chương trình</h2><p class="ct-panel-subtitle">Mở môn để quản lý syllabus, chương bài và tài liệu.</p></div><button class="ct-btn" type="button" @click="openCreateMon">Thêm môn</button></div><div v-if="loading" class="ct-loading">Đang tải khung chương trình...</div><div v-else-if="error" class="ct-error">{{ error }}</div><div v-else class="ct-table-wrap"><table class="ct-table"><thead><tr><th>Mã môn CT</th><th>Môn học</th><th>Nhóm</th><th>Tín chỉ</th><th>Giờ</th><th>Tính chất</th><th class="ct-right">Thao tác</th></tr></thead><tbody><tr v-for="mon in monRowsLoc" :key="layIdBanGhi(mon)" class="ct-clickable-row" @dblclick="goMon(mon)"><td><span class="ct-badge">{{ mon.maMonTrongCt || '—' }}</span></td><td class="ct-strong">{{ tenMonHoc(mon) }}</td><td>{{ tenNhom(mon.nhomKienThucId) }}</td><td>{{ mon.soTinChi || '—' }}</td><td>{{ mon.tongGio || '—' }}</td><td><span :class="['ct-badge',mon.batBuoc?'ok':'warn']">{{ mon.batBuoc ? 'Bắt buộc' : 'Tự chọn' }}</span></td><td class="ct-right"><span class="ct-row-actions"><RouterLink class="ct-btn small ghost" :to="`/quy-trinh/chuong-trinh/${chuongTrinhId}/phien-ban/${versionId}/mon/${layIdBanGhi(mon)}`">Mở</RouterLink><button class="ct-btn small light" type="button" @click="openEditMon(mon)">Sửa</button><button class="ct-btn small danger" type="button" @click="removeMon(mon)">Xóa</button></span></td></tr><tr v-if="!monRowsLoc.length"><td colspan="7" class="ct-empty">Chưa có môn trong nhóm này.</td></tr></tbody></table></div></section></section>
    </main></div>
    <BieuMauQuanLyModal v-model="nhomForm" :open="nhomModal" :mode="nhomMode" :fields="nhomFields" :saving="saving" title="Nhóm kiến thức" @close="nhomModal=false" @submit="saveNhom" />
    <BieuMauQuanLyModal v-model="monForm" :open="monModal" :mode="monMode" :fields="monFields" :saving="saving" title="Môn trong chương trình" @close="monModal=false" @submit="saveMon" />
  </section>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue';import { useRoute, useRouter } from 'vue-router';import './luongChuongTrinh.css';import BieuMauQuanLyModal from '@/modules/chuongTrinh/components/modal/BieuMauQuanLyModal.vue';import { CHUONG_TRINH_RESOURCE_MAP } from '@/modules/chuongTrinh/constants/trangThaiChuongTrinh.js';import { API_LUONG_CHUONG_TRINH, capNhatBanGhi, layDanhSachMonHoc, layDanhSachMonTrongChuongTrinh, layDanhSachNhomKienThuc, layIdBanGhi, locTheoGiaTri, taoBanGhi, taoNhanMonHoc, xoaBanGhi } from '@/modules/chuongTrinh/services/luongChuongTrinhDaoTaoService.js';
const route=useRoute();const router=useRouter();const chuongTrinhId=computed(()=>route.params.chuongTrinhId);const versionId=computed(()=>route.params.versionId);const activeNhomId=ref('');const nhomRows=ref([]);const monRows=ref([]);const danhMucMon=ref([]);const loading=ref(false);const saving=ref(false);const error=ref('');const nhomFields=CHUONG_TRINH_RESOURCE_MAP['nhom-kien-thuc'].fields;const monFields=CHUONG_TRINH_RESOURCE_MAP['chuong-trinh-mon'].fields;const nhomModal=ref(false);const monModal=ref(false);const nhomMode=ref('create');const monMode=ref('create');const nhomForm=ref({});const monForm=ref({});
const monRowsLoc=computed(()=>activeNhomId.value?locTheoGiaTri(monRows.value,'nhomKienThucId',activeNhomId.value):monRows.value);const tongTinChi=computed(()=>monRows.value.reduce((sum,item)=>sum+(Number(item.soTinChi)||0),0));
const tenMonHoc=(mon)=>{const dm=danhMucMon.value.find(x=>String(layIdBanGhi(x))===String(mon.monHocId));return dm?taoNhanMonHoc({...dm,maMonTrongCt:mon.maMonTrongCt}):taoNhanMonHoc(mon);};const tenNhom=(id)=>{const n=nhomRows.value.find(item=>String(layIdBanGhi(item))===String(id));return n?.ten||n?.tenNhom||n?.ma||id||'—';};const demMonTheoNhom=(id)=>monRows.value.filter(mon=>String(mon.nhomKienThucId)===String(id)).length;const goMon=(mon)=>{const id=layIdBanGhi(mon);if(id)router.push(`/quy-trinh/chuong-trinh/${chuongTrinhId.value}/phien-ban/${versionId.value}/mon/${id}`);};
const loadData=async()=>{loading.value=true;error.value='';try{const [nhom,mon,dm]=await Promise.all([layDanhSachNhomKienThuc({chuongTrinhVersionId:versionId.value}),layDanhSachMonTrongChuongTrinh({chuongTrinhVersionId:versionId.value}),layDanhSachMonHoc()]);nhomRows.value=locTheoGiaTri(nhom,'chuongTrinhVersionId',versionId.value);monRows.value=locTheoGiaTri(mon,'chuongTrinhVersionId',versionId.value);danhMucMon.value=dm;}catch(err){error.value=err?.message||'Không tải được khung chương trình.';}finally{loading.value=false;}};
const openCreateNhom=()=>{nhomMode.value='create';nhomForm.value={chuongTrinhVersionId:Number(versionId.value)};nhomModal.value=true;};const openCreateMon=()=>{monMode.value='create';monForm.value={chuongTrinhVersionId:Number(versionId.value),nhomKienThucId:activeNhomId.value||''};monModal.value=true;};const openEditMon=(item)=>{monMode.value='edit';monForm.value={...item};monModal.value=true;};
const saveNhom=async()=>{saving.value=true;try{const id=layIdBanGhi(nhomForm.value);if(nhomMode.value==='edit'&&id)await capNhatBanGhi(API_LUONG_CHUONG_TRINH.NHOM_KIEN_THUC,id,nhomForm.value);else await taoBanGhi(API_LUONG_CHUONG_TRINH.NHOM_KIEN_THUC,nhomForm.value);nhomModal.value=false;await loadData();}finally{saving.value=false;}};const saveMon=async()=>{saving.value=true;try{const id=layIdBanGhi(monForm.value);if(monMode.value==='edit'&&id)await capNhatBanGhi(API_LUONG_CHUONG_TRINH.MON_TRONG_CHUONG_TRINH,id,monForm.value);else await taoBanGhi(API_LUONG_CHUONG_TRINH.MON_TRONG_CHUONG_TRINH,monForm.value);monModal.value=false;await loadData();}finally{saving.value=false;}};const removeMon=async(item)=>{const id=layIdBanGhi(item);if(id&&confirm('Xóa môn khỏi chương trình?')){await xoaBanGhi(API_LUONG_CHUONG_TRINH.MON_TRONG_CHUONG_TRINH,id);await loadData();}};
onMounted(loadData);
</script>
