export const CHUONG_TRINH_FLOW = [
  'nganh',
  'trinh-do-dao-tao',
  'loai-chuong-trinh',
  'chuong-trinh',
  'chuong-trinh-version',
  'syllabus-chuong-trinh',
  'muc-tieu-chuong-trinh',
  'nang-luc-dau-ra',
  'vi-tri-viec-lam',
  'khung-ky',
  'nhom-kien-thuc',
  'mon-hoc',
  'chuong-trinh-mon',
  'mon-tien-quyet',
  'nhom-tu-chon',
  'syllabus-mon-hoc',
  'syllabus-chuong-bai',
  'syllabus-tai-lieu',
  'dieu-kien-mon-hoc',
  'quy-doi-diem',
  'dieu-kien-tot-nghiep',
];

export const CHUONG_TRINH_RELATIONS = {
  nganh: { childKey: 'trinh-do-dao-tao', childLabel: 'Trình độ đào tạo' },
  'trinh-do-dao-tao': { childKey: 'loai-chuong-trinh', childLabel: 'Loại chương trình' },
  'loai-chuong-trinh': { childKey: 'chuong-trinh', childLabel: 'Chương trình đào tạo' },
  'chuong-trinh': {
    childKey: 'chuong-trinh-version',
    childLabel: 'Phiên bản chương trình',
    linkField: 'chuongTrinhId',
    sourceResource: 'chuong-trinh',
  },
  'chuong-trinh-version': {
    childKey: 'syllabus-chuong-trinh',
    childLabel: 'Syllabus chương trình',
    linkField: 'chuongTrinhVersionId',
    sourceResource: 'chuong-trinh-version',
  },
  'syllabus-chuong-trinh': { childKey: 'muc-tieu-chuong-trinh', childLabel: 'Mục tiêu chương trình' },
  'muc-tieu-chuong-trinh': { childKey: 'nang-luc-dau-ra', childLabel: 'Năng lực đầu ra' },
  'nang-luc-dau-ra': { childKey: 'vi-tri-viec-lam', childLabel: 'Vị trí việc làm' },
  'vi-tri-viec-lam': { childKey: 'khung-ky', childLabel: 'Khung kỳ' },
  'khung-ky': { childKey: 'nhom-kien-thuc', childLabel: 'Nhóm kiến thức' },
  'nhom-kien-thuc': { childKey: 'mon-hoc', childLabel: 'Môn học' },
  'mon-hoc': { childKey: 'chuong-trinh-mon', childLabel: 'Môn trong chương trình' },
  'chuong-trinh-mon': {
    childKey: 'mon-tien-quyet',
    childLabel: 'Môn tiên quyết',
    linkField: 'monId',
    sourceResource: 'chuong-trinh-mon',
  },
  'mon-tien-quyet': { childKey: 'nhom-tu-chon', childLabel: 'Nhóm tự chọn' },
  'nhom-tu-chon': { childKey: 'syllabus-mon-hoc', childLabel: 'Syllabus môn học' },
  'syllabus-mon-hoc': {
    childKey: 'syllabus-chuong-bai',
    childLabel: 'Chương/bài syllabus',
    linkField: 'syllabusMonId',
    sourceResource: 'syllabus-mon-hoc',
  },
  'syllabus-chuong-bai': { childKey: 'syllabus-tai-lieu', childLabel: 'Tài liệu môn học' },
  'syllabus-tai-lieu': { childKey: 'dieu-kien-mon-hoc', childLabel: 'Điều kiện môn học' },
  'dieu-kien-mon-hoc': { childKey: 'quy-doi-diem', childLabel: 'Quy đổi điểm' },
  'quy-doi-diem': { childKey: 'dieu-kien-tot-nghiep', childLabel: 'Điều kiện tốt nghiệp' },
};

export const ROUTE_ID_PARAM_BY_RESOURCE = {
  nganh: 'nganhId',
  'trinh-do-dao-tao': 'trinhDoId',
  'loai-chuong-trinh': 'loaiChuongTrinhId',
  'chuong-trinh': 'chuongTrinhId',
  'chuong-trinh-version': 'chuongTrinhVersionId',
  'syllabus-chuong-trinh': 'syllabusChuongTrinhId',
  'muc-tieu-chuong-trinh': 'mucTieuChuongTrinhId',
  'nang-luc-dau-ra': 'nangLucDauRaId',
  'vi-tri-viec-lam': 'viTriViecLamId',
  'khung-ky': 'khungKyId',
  'nhom-kien-thuc': 'nhomKienThucId',
  'mon-hoc': 'monHocId',
  'chuong-trinh-mon': 'chuongTrinhMonId',
  'mon-tien-quyet': 'monTienQuyetId',
  'nhom-tu-chon': 'nhomTuChonId',
  'syllabus-mon-hoc': 'syllabusMonHocId',
  'syllabus-chuong-bai': 'syllabusChuongBaiId',
  'syllabus-tai-lieu': 'syllabusTaiLieuId',
  'dieu-kien-mon-hoc': 'dieuKienMonHocId',
  'quy-doi-diem': 'quyDoiDiemId',
  'dieu-kien-tot-nghiep': 'dieuKienTotNghiepId',
};

export const ROUTE_CONTEXT_TO_FIELD = {
  nganh: { nganhId: 'nganhId' },
  'trinh-do-dao-tao': { trinhDoId: 'trinhDoId' },
  'loai-chuong-trinh': { loaiChuongTrinhId: 'loaiChuongTrinhId' },
  'chuong-trinh': { chuongTrinhId: 'chuongTrinhId' },
  'chuong-trinh-version': { chuongTrinhVersionId: 'chuongTrinhVersionId' },
  'mon-hoc': { monHocId: 'monHocId' },
  'chuong-trinh-mon': { chuongTrinhMonId: 'chuongTrinhMonId', monId: 'monId' },
  'syllabus-mon-hoc': { syllabusMonHocId: 'syllabusMonId' },
};

export const RESOURCE_FILTERS = {
  'chuong-trinh': [
    { sourceResource: 'nganh', field: 'nganhId' },
    { sourceResource: 'trinh-do-dao-tao', field: 'trinhDoId' },
    { sourceResource: 'loai-chuong-trinh', field: 'loaiChuongTrinhId' },
  ],
  'chuong-trinh-version': [{ sourceResource: 'chuong-trinh', field: 'chuongTrinhId' }],
  'syllabus-chuong-trinh': [{ sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' }],
  'muc-tieu-chuong-trinh': [{ sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' }],
  'nang-luc-dau-ra': [{ sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' }],
  'vi-tri-viec-lam': [{ sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' }],
  'khung-ky': [{ sourceResource: 'loai-chuong-trinh', field: 'loaiChuongTrinhId' }],
  'nhom-kien-thuc': [{ sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' }],
  'chuong-trinh-mon': [
    { sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' },
    { sourceResource: 'mon-hoc', field: 'monHocId' },
  ],
  'mon-tien-quyet': [{ sourceResource: 'chuong-trinh-mon', field: 'monId' }],
  'nhom-tu-chon': [{ sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' }],
  'syllabus-mon-hoc': [{ sourceResource: 'chuong-trinh-mon', field: 'chuongTrinhMonId' }],
  'syllabus-chuong-bai': [{ sourceResource: 'syllabus-mon-hoc', field: 'syllabusMonId' }],
  'syllabus-tai-lieu': [{ sourceResource: 'syllabus-mon-hoc', field: 'syllabusMonId' }],
  'dieu-kien-mon-hoc': [{ sourceResource: 'syllabus-mon-hoc', field: 'syllabusMonId' }],
  'quy-doi-diem': [{ sourceResource: 'chuong-trinh-mon', field: 'chuongTrinhMonId' }],
  'dieu-kien-tot-nghiep': [{ sourceResource: 'chuong-trinh-version', field: 'chuongTrinhVersionId' }],
};
