import {
  getAllChuongTrinh,
  getAllChuongTrinhMon,
  getAllChuongTrinhVersion,
  getAllDieuKienMonHoc,
  getAllDieuKienTotNghiep,
  getAllMonHoc,
  getAllMonTienQuyet,
  getAllMonTuChon,
  getAllMucTieuChuongTrinh,
  getAllNangLucDauRa,
  getAllNhomKienThuc,
  getAllNhomTuChon,
  getAllQuyDoiDiem,
  getAllSyllabusChuongBai,
  getAllSyllabusChuongTrinh,
  getAllSyllabusMonHoc,
  getAllSyllabusTaiLieu,
  getAllViTriViecLam,
} from '@/api/chuongTrinh/ApiRespone/index.js';
import {
  createChuongTrinh,
  createChuongTrinhMon,
  createChuongTrinhVersion,
  createDieuKienMonHoc,
  createDieuKienTotNghiep,
  createMonHoc,
  createMonTienQuyet,
  createMonTuChon,
  createMucTieuChuongTrinh,
  createNangLucDauRa,
  createNhomKienThuc,
  createNhomTuChon,
  createQuyDoiDiem,
  createSyllabusChuongBai,
  createSyllabusChuongTrinh,
  createSyllabusMonHoc,
  createSyllabusTaiLieu,
  createViTriViecLam,
  deleteChuongTrinh,
  deleteChuongTrinhMon,
  deleteChuongTrinhVersion,
  deleteDieuKienMonHoc,
  deleteDieuKienTotNghiep,
  deleteMonHoc,
  deleteMonTienQuyet,
  deleteMonTuChon,
  deleteMucTieuChuongTrinh,
  deleteNangLucDauRa,
  deleteNhomKienThuc,
  deleteNhomTuChon,
  deleteQuyDoiDiem,
  deleteSyllabusChuongBai,
  deleteSyllabusChuongTrinh,
  deleteSyllabusMonHoc,
  deleteSyllabusTaiLieu,
  deleteViTriViecLam,
  updateChuongTrinh,
  updateChuongTrinhMon,
  updateChuongTrinhVersion,
  updateDieuKienMonHoc,
  updateDieuKienTotNghiep,
  updateMonHoc,
  updateMonTienQuyet,
  updateMonTuChon,
  updateMucTieuChuongTrinh,
  updateNangLucDauRa,
  updateNhomKienThuc,
  updateNhomTuChon,
  updateQuyDoiDiem,
  updateSyllabusChuongBai,
  updateSyllabusChuongTrinh,
  updateSyllabusMonHoc,
  updateSyllabusTaiLieu,
  updateViTriViecLam,
} from '@/api/chuongTrinh/ApiRequest/index.js';

const field = (key, label, type = 'text', extras = {}) => ({
  key,
  label,
  type,
  ...extras,
});

export const CHUONG_TRINH_DATA_SOURCES = {
  programs: getAllChuongTrinh,
  versions: getAllChuongTrinhVersion,
  syllabusPrograms: getAllSyllabusChuongTrinh,
  objectives: getAllMucTieuChuongTrinh,
  competencies: getAllNangLucDauRa,
  jobPositions: getAllViTriViecLam,
  graduationConditions: getAllDieuKienTotNghiep,
  subjects: getAllMonHoc,
  groups: getAllNhomKienThuc,
  courses: getAllChuongTrinhMon,
  prerequisites: getAllMonTienQuyet,
  electiveGroups: getAllNhomTuChon,
  electiveCourses: getAllMonTuChon,
  syllabusSubjects: getAllSyllabusMonHoc,
  syllabusLessons: getAllSyllabusChuongBai,
  syllabusMaterials: getAllSyllabusTaiLieu,
  courseConditions: getAllDieuKienMonHoc,
  scoreConversions: getAllQuyDoiDiem,
};

export const CHUONG_TRINH_PAGE_CONFIG = {
  'chuong-trinh': {
    title: 'Chương trình đào tạo',
    subtitle: 'Quản lý chương trình gốc theo ngành, trình độ, loại chương trình và thời gian đào tạo.',
    dataKey: 'programs',
    scope: 'none',
    searchFields: ['maChuongTrinh', 'tenChuongTrinh', 'doiTuongTuyenSinh', 'thoiGianDaoTao'],
    columns: [
      { key: 'maChuongTrinh', label: 'Mã chương trình' },
      { key: 'tenChuongTrinh', label: 'Tên chương trình' },
      { key: 'nganhId', label: 'Ngành', format: 'nganh' },
      { key: 'trinhDoId', label: 'Trình độ', format: 'trinhDo' },
      { key: 'loaiChuongTrinhId', label: 'Loại', format: 'loaiChuongTrinh' },
      { key: 'thoiGianDaoTao', label: 'Thời gian đào tạo' },
    ],
    fields: [
      field('nganhId', 'Ngành', 'select', { optionKey: 'nganh', required: true }),
      field('trinhDoId', 'Trình độ', 'select', { optionKey: 'trinhDo', required: true }),
      field('loaiChuongTrinhId', 'Loại chương trình', 'select', { optionKey: 'loaiChuongTrinh', required: true }),
      field('maChuongTrinh', 'Mã chương trình', 'text', { required: true }),
      field('tenChuongTrinh', 'Tên chương trình', 'text', { required: true, wide: true }),
      field('doiTuongTuyenSinh', 'Đối tượng tuyển sinh', 'textarea', { wide: true }),
      field('thoiGianDaoTao', 'Thời gian đào tạo'),
    ],
    create: createChuongTrinh,
    update: updateChuongTrinh,
    remove: deleteChuongTrinh,
  },
  'chuong-trinh-version': {
    title: 'Version chương trình',
    subtitle: 'Theo dõi phiên bản ban hành, quyết định áp dụng và tổng hợp khối lượng đào tạo.',
    dataKey: 'versions',
    scope: 'program',
    searchFields: ['maVersion', 'tenVersion', 'soQuyetDinh', 'nguoiKy', 'coQuanBanHanh'],
    columns: [
      { key: 'chuongTrinhId', label: 'Chương trình', format: 'program' },
      { key: 'maVersion', label: 'Mã version' },
      { key: 'tenVersion', label: 'Tên version' },
      { key: 'ngayApDung', label: 'Ngày áp dụng', format: 'date' },
      { key: 'tongTinChi', label: 'Tổng tín chỉ', format: 'number' },
      { key: 'laHienHanh', label: 'Hiện hành', format: 'boolean' },
    ],
    fields: [
      field('chuongTrinhId', 'Chương trình', 'select', { optionKey: 'program', required: true }),
      field('maVersion', 'Mã version', 'text', { required: true }),
      field('tenVersion', 'Tên version', 'text', { required: true, wide: true }),
      field('ngayApDung', 'Ngày áp dụng', 'date'),
      field('ngayHetHieuLuc', 'Ngày hết hiệu lực', 'date'),
      field('soQuyetDinh', 'Số quyết định'),
      field('ngayQuyetDinh', 'Ngày quyết định', 'date'),
      field('nguoiKy', 'Người ký'),
      field('coQuanBanHanh', 'Cơ quan ban hành'),
      field('fileQuyetDinh', 'File quyết định'),
      field('tongTinChi', 'Tổng tín chỉ', 'number'),
      field('tongSoGio', 'Tổng số giờ', 'number'),
      field('tongGioLyThuyet', 'Tổng giờ lý thuyết', 'number'),
      field('tongGioThucHanh', 'Tổng giờ thực hành', 'number'),
      field('tongGioKiemTra', 'Tổng giờ kiểm tra', 'number'),
      field('laHienHanh', 'Là hiện hành', 'checkbox'),
    ],
    create: createChuongTrinhVersion,
    update: updateChuongTrinhVersion,
    remove: deleteChuongTrinhVersion,
  },
  'syllabus-chuong-trinh': {
    title: 'Syllabus chương trình',
    subtitle: 'Lưu mô tả tổng quan, mục đích và phương pháp đào tạo cho từng version chương trình.',
    dataKey: 'syllabusPrograms',
    scope: 'version',
    searchFields: ['moTaTongQuan', 'mucDich', 'yeuCauDaoTao', 'phuongPhapDaoTao', 'ghiChu'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'moTaTongQuan', label: 'Mô tả tổng quan' },
      { key: 'mucDich', label: 'Mục đích' },
      { key: 'phuongPhapDaoTao', label: 'Phương pháp đào tạo' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('moTaTongQuan', 'Mô tả tổng quan', 'textarea', { wide: true }),
      field('mucDich', 'Mục đích', 'textarea', { wide: true }),
      field('yeuCauDaoTao', 'Yêu cầu đào tạo', 'textarea', { wide: true }),
      field('phuongPhapDaoTao', 'Phương pháp đào tạo', 'textarea', { wide: true }),
      field('ghiChu', 'Ghi chú', 'textarea', { wide: true }),
    ],
    create: createSyllabusChuongTrinh,
    update: updateSyllabusChuongTrinh,
    remove: deleteSyllabusChuongTrinh,
  },
  'muc-tieu-chuong-trinh': {
    title: 'Mục tiêu chương trình',
    subtitle: 'Khai báo các mục tiêu theo nhóm kiến thức, kỹ năng và năng lực tự chủ.',
    dataKey: 'objectives',
    scope: 'version',
    searchFields: ['loai', 'noiDung'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'loai', label: 'Loại' },
      { key: 'noiDung', label: 'Nội dung' },
      { key: 'thuTu', label: 'Thứ tự', format: 'number' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('loai', 'Loại mục tiêu', 'select', { optionKey: 'mucTieuLoai', required: true }),
      field('noiDung', 'Nội dung', 'textarea', { wide: true, required: true }),
      field('thuTu', 'Thứ tự', 'number'),
    ],
    create: createMucTieuChuongTrinh,
    update: updateMucTieuChuongTrinh,
    remove: deleteMucTieuChuongTrinh,
  },
  'nang-luc-dau-ra': {
    title: 'Năng lực đầu ra',
    subtitle: 'Quản lý mã năng lực, mô tả chi tiết và thứ tự hiển thị cho từng version.',
    dataKey: 'competencies',
    scope: 'version',
    searchFields: ['ma', 'noiDung', 'loai'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'ma', label: 'Mã' },
      { key: 'noiDung', label: 'Nội dung' },
      { key: 'loai', label: 'Loại' },
      { key: 'thuTu', label: 'Thứ tự', format: 'number' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('ma', 'Mã năng lực', 'text', { required: true }),
      field('noiDung', 'Nội dung', 'textarea', { wide: true, required: true }),
      field('loai', 'Loại năng lực', 'select', { optionKey: 'nangLucLoai', required: true }),
      field('thuTu', 'Thứ tự', 'number'),
    ],
    create: createNangLucDauRa,
    update: updateNangLucDauRa,
    remove: deleteNangLucDauRa,
  },
  'vi-tri-viec-lam': {
    title: 'Vị trí việc làm',
    subtitle: 'Danh mục vị trí việc làm đầu ra gắn theo từng version chương trình.',
    dataKey: 'jobPositions',
    scope: 'version',
    searchFields: ['ten', 'moTa'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'ten', label: 'Tên vị trí' },
      { key: 'moTa', label: 'Mô tả' },
      { key: 'thuTu', label: 'Thứ tự', format: 'number' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('ten', 'Tên vị trí', 'text', { required: true }),
      field('moTa', 'Mô tả', 'textarea', { wide: true }),
      field('thuTu', 'Thứ tự', 'number'),
    ],
    create: createViTriViecLam,
    update: updateViTriViecLam,
    remove: deleteViTriViecLam,
  },
  'dieu-kien-tot-nghiep': {
    title: 'Điều kiện tốt nghiệp',
    subtitle: 'Theo dõi điều kiện tốt nghiệp áp dụng cho từng version chương trình.',
    dataKey: 'graduationConditions',
    scope: 'version',
    searchFields: ['noiDung'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'noiDung', label: 'Nội dung' },
      { key: 'thuTu', label: 'Thứ tự', format: 'number' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('noiDung', 'Nội dung', 'textarea', { wide: true, required: true }),
      field('thuTu', 'Thứ tự', 'number'),
    ],
    create: createDieuKienTotNghiep,
    update: updateDieuKienTotNghiep,
    remove: deleteDieuKienTotNghiep,
  },
  'mon-hoc': {
    title: 'Môn học',
    subtitle: 'Danh mục môn học gốc dùng để cấu hình các học phần trong chương trình.',
    dataKey: 'subjects',
    scope: 'none',
    searchFields: ['maMon', 'tenMon', 'moTa'],
    columns: [
      { key: 'maMon', label: 'Mã môn' },
      { key: 'tenMon', label: 'Tên môn' },
      { key: 'moTa', label: 'Mô tả' },
    ],
    fields: [
      field('maMon', 'Mã môn', 'text', { required: true }),
      field('tenMon', 'Tên môn', 'text', { required: true, wide: true }),
      field('moTa', 'Mô tả', 'textarea', { wide: true }),
    ],
    create: createMonHoc,
    update: updateMonHoc,
    remove: deleteMonHoc,
  },
  'nhom-kien-thuc': {
    title: 'Nhóm kiến thức',
    subtitle: 'Khai báo nhóm kiến thức, loại nhóm và tổng khối lượng học tập theo version.',
    dataKey: 'groups',
    scope: 'version',
    searchFields: ['ma', 'ten', 'loaiNhom'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'ma', label: 'Mã nhóm' },
      { key: 'ten', label: 'Tên nhóm' },
      { key: 'loaiNhom', label: 'Loại nhóm' },
      { key: 'tongTinChi', label: 'Tổng tín chỉ', format: 'number' },
      { key: 'tongSoGio', label: 'Tổng số giờ', format: 'number' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('ma', 'Mã nhóm', 'text', { required: true }),
      field('ten', 'Tên nhóm', 'text', { required: true, wide: true }),
      field('thuTu', 'Thứ tự', 'number'),
      field('loaiNhom', 'Loại nhóm', 'select', { optionKey: 'loaiNhom', required: true }),
      field('tongTinChi', 'Tổng tín chỉ', 'number'),
      field('tongSoGio', 'Tổng số giờ', 'number'),
      field('tongGioLyThuyet', 'Giờ lý thuyết', 'number'),
      field('tongGioThucHanh', 'Giờ thực hành', 'number'),
      field('tongGioKiemTra', 'Giờ kiểm tra', 'number'),
    ],
    create: createNhomKienThuc,
    update: updateNhomKienThuc,
    remove: deleteNhomKienThuc,
  },
  'chuong-trinh-mon': {
    title: 'Môn trong chương trình',
    subtitle: 'Liên kết môn học với version chương trình, khung kỳ và nhóm kiến thức.',
    dataKey: 'courses',
    scope: 'version',
    searchFields: ['maMonTrongCt', 'loai', 'loaiHocPhan', 'ghiChu'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'monHocId', label: 'Môn học', format: 'subject' },
      { key: 'maMonTrongCt', label: 'Mã môn trong CT' },
      { key: 'khungKyId', label: 'Khung kỳ', format: 'khungKy' },
      { key: 'nhomKienThucId', label: 'Nhóm kiến thức', format: 'group' },
      { key: 'soTinChi', label: 'Số tín chỉ', format: 'number' },
      { key: 'batBuoc', label: 'Bắt buộc', format: 'boolean' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('monHocId', 'Môn học', 'select', { optionKey: 'subject', required: true }),
      field('maMonTrongCt', 'Mã môn trong CT', 'text', { required: true }),
      field('khungKyId', 'Khung kỳ', 'select', { optionKey: 'khungKy' }),
      field('nhomKienThucId', 'Nhóm kiến thức', 'select', { optionKey: 'group' }),
      field('loai', 'Loại', 'select', { optionKey: 'loaiHocPhanCt' }),
      field('loaiHocPhan', 'Loại học phần', 'select', { optionKey: 'loaiHocPhanType' }),
      field('batBuoc', 'Bắt buộc', 'checkbox'),
      field('laMonDieuKien', 'Là môn điều kiện', 'checkbox'),
      field('thuTu', 'Thứ tự', 'number'),
      field('soTinChi', 'Số tín chỉ', 'number'),
      field('tongGio', 'Tổng giờ', 'number'),
      field('gioLyThuyet', 'Giờ lý thuyết', 'number'),
      field('gioThucHanh', 'Giờ thực hành', 'number'),
      field('gioKiemTra', 'Giờ kiểm tra', 'number'),
      field('ghiChu', 'Ghi chú', 'textarea', { wide: true }),
    ],
    create: createChuongTrinhMon,
    update: updateChuongTrinhMon,
    remove: deleteChuongTrinhMon,
  },
  'mon-tien-quyet': {
    title: 'Môn tiên quyết',
    subtitle: 'Thiết lập quan hệ tiên quyết, học trước hoặc song hành giữa các môn trong chương trình.',
    dataKey: 'prerequisites',
    scope: 'course',
    searchFields: ['loai', 'ghiChu'],
    columns: [
      { key: 'monId', label: 'Môn chính', format: 'course' },
      { key: 'monDieuKienId', label: 'Môn điều kiện', format: 'course' },
      { key: 'loai', label: 'Loại' },
      { key: 'ghiChu', label: 'Ghi chú' },
    ],
    fields: [
      field('monId', 'Môn chính', 'select', { optionKey: 'course', required: true }),
      field('monDieuKienId', 'Môn điều kiện', 'select', { optionKey: 'course', required: true }),
      field('loai', 'Loại điều kiện', 'select', { optionKey: 'monTienQuyetLoai', required: true }),
      field('ghiChu', 'Ghi chú', 'textarea', { wide: true }),
    ],
    create: createMonTienQuyet,
    update: updateMonTienQuyet,
    remove: deleteMonTienQuyet,
  },
  'nhom-tu-chon': {
    title: 'Nhóm tự chọn',
    subtitle: 'Quản lý nhóm tự chọn và số tín chỉ cần đạt trong từng version.',
    dataKey: 'electiveGroups',
    scope: 'version',
    searchFields: ['ten', 'ghiChu'],
    columns: [
      { key: 'chuongTrinhVersionId', label: 'Version', format: 'version' },
      { key: 'ten', label: 'Tên nhóm' },
      { key: 'soMonChon', label: 'Số môn chọn', format: 'number' },
      { key: 'soTinChiCanDat', label: 'Số tín chỉ cần đạt', format: 'number' },
      { key: 'ghiChu', label: 'Ghi chú' },
    ],
    fields: [
      field('chuongTrinhVersionId', 'Version chương trình', 'select', { optionKey: 'version', required: true }),
      field('ten', 'Tên nhóm', 'text', { required: true, wide: true }),
      field('soMonChon', 'Số môn chọn', 'number'),
      field('soTinChiCanDat', 'Số tín chỉ cần đạt', 'number'),
      field('ghiChu', 'Ghi chú', 'textarea', { wide: true }),
    ],
    create: createNhomTuChon,
    update: updateNhomTuChon,
    remove: deleteNhomTuChon,
  },
  'mon-tu-chon': {
    title: 'Môn tự chọn',
    subtitle: 'Gắn môn trong chương trình vào nhóm tự chọn theo cấu trúc DB hiện tại.',
    dataKey: 'electiveCourses',
    scope: 'course',
    searchFields: [],
    columns: [
      { key: 'nhomId', label: 'Nhóm tự chọn', format: 'electiveGroup' },
      { key: 'chuongTrinhMonId', label: 'Môn trong CT', format: 'course' },
    ],
    fields: [
      field('nhomId', 'Nhóm tự chọn', 'select', { optionKey: 'electiveGroup', required: true }),
      field('chuongTrinhMonId', 'Môn trong chương trình', 'select', { optionKey: 'course', required: true }),
    ],
    create: createMonTuChon,
    update: updateMonTuChon,
    remove: deleteMonTuChon,
  },
  'syllabus-mon-hoc': {
    title: 'Syllabus môn học',
    subtitle: 'Khai báo vị trí, tính chất, đánh giá và điều kiện hoàn thành cho từng môn trong chương trình.',
    dataKey: 'syllabusSubjects',
    scope: 'course',
    searchFields: ['viTri', 'tinhChat', 'mucTieu', 'phuongPhapDanhGia', 'dieuKienHoanThanh'],
    columns: [
      { key: 'chuongTrinhMonId', label: 'Môn trong CT', format: 'course' },
      { key: 'viTri', label: 'Vị trí' },
      { key: 'tinhChat', label: 'Tính chất' },
      { key: 'diemDatToiThieu', label: 'Điểm đạt tối thiểu', format: 'number' },
      { key: 'donViDiem', label: 'Đơn vị điểm' },
      { key: 'batBuocDuThi', label: 'Bắt buộc dự thi', format: 'boolean' },
    ],
    fields: [
      field('chuongTrinhMonId', 'Môn trong chương trình', 'select', { optionKey: 'course', required: true }),
      field('viTri', 'Vị trí'),
      field('tinhChat', 'Tính chất'),
      field('mucTieu', 'Mục tiêu', 'textarea', { wide: true }),
      field('phuongPhapDanhGia', 'Phương pháp đánh giá', 'textarea', { wide: true }),
      field('dieuKienHoanThanh', 'Điều kiện hoàn thành', 'textarea', { wide: true }),
      field('huongDan', 'Hướng dẫn', 'textarea', { wide: true }),
      field('diemDatToiThieu', 'Điểm đạt tối thiểu', 'number'),
      field('donViDiem', 'Đơn vị điểm', 'select', { optionKey: 'donViDiem' }),
      field('tyLeChuyenCanToiThieu', 'Tỷ lệ chuyên cần tối thiểu', 'number'),
      field('batBuocDuThi', 'Bắt buộc dự thi', 'checkbox'),
      field('congThucQuyDoi', 'Công thức quy đổi', 'textarea', { wide: true }),
    ],
    create: createSyllabusMonHoc,
    update: updateSyllabusMonHoc,
    remove: deleteSyllabusMonHoc,
  },
  'syllabus-chuong-bai': {
    title: 'Syllabus chương bài',
    subtitle: 'Quản lý nội dung chương bài, mục tiêu và phân bổ giờ học theo syllabus môn học.',
    dataKey: 'syllabusLessons',
    scope: 'syllabus',
    searchFields: ['ten', 'noiDung', 'mucTieu'],
    columns: [
      { key: 'syllabusMonId', label: 'Syllabus môn học', format: 'syllabusMon' },
      { key: 'ten', label: 'Tên chương bài' },
      { key: 'tongGio', label: 'Tổng giờ', format: 'number' },
      { key: 'thuTu', label: 'Thứ tự', format: 'number' },
    ],
    fields: [
      field('syllabusMonId', 'Syllabus môn học', 'select', { optionKey: 'syllabusMon', required: true }),
      field('ten', 'Tên chương bài', 'text', { required: true, wide: true }),
      field('tongGio', 'Tổng giờ', 'number'),
      field('gioLyThuyet', 'Giờ lý thuyết', 'number'),
      field('gioThucHanh', 'Giờ thực hành', 'number'),
      field('gioKiemTra', 'Giờ kiểm tra', 'number'),
      field('noiDung', 'Nội dung', 'textarea', { wide: true }),
      field('mucTieu', 'Mục tiêu', 'textarea', { wide: true }),
      field('thuTu', 'Thứ tự', 'number'),
    ],
    create: createSyllabusChuongBai,
    update: updateSyllabusChuongBai,
    remove: deleteSyllabusChuongBai,
  },
  'syllabus-tai-lieu': {
    title: 'Tài liệu syllabus',
    subtitle: 'Danh mục tài liệu học tập gắn với từng syllabus môn học.',
    dataKey: 'syllabusMaterials',
    scope: 'syllabus',
    searchFields: ['ten', 'tacGia', 'nhaXuatBan', 'loai', 'ghiChu'],
    columns: [
      { key: 'syllabusMonId', label: 'Syllabus môn học', format: 'syllabusMon' },
      { key: 'ten', label: 'Tên tài liệu' },
      { key: 'tacGia', label: 'Tác giả' },
      { key: 'namXuatBan', label: 'Năm XB', format: 'number' },
      { key: 'loai', label: 'Loại' },
    ],
    fields: [
      field('syllabusMonId', 'Syllabus môn học', 'select', { optionKey: 'syllabusMon', required: true }),
      field('ten', 'Tên tài liệu', 'text', { required: true, wide: true }),
      field('tacGia', 'Tác giả'),
      field('namXuatBan', 'Năm xuất bản', 'number'),
      field('nhaXuatBan', 'Nhà xuất bản'),
      field('loai', 'Loại tài liệu'),
      field('ghiChu', 'Ghi chú', 'textarea', { wide: true }),
    ],
    create: createSyllabusTaiLieu,
    update: updateSyllabusTaiLieu,
    remove: deleteSyllabusTaiLieu,
  },
  'dieu-kien-mon-hoc': {
    title: 'Điều kiện môn học',
    subtitle: 'Khai báo điều kiện về học liệu, thiết bị và yêu cầu triển khai cho môn học.',
    dataKey: 'courseConditions',
    scope: 'syllabus',
    searchFields: ['loai', 'noiDung'],
    columns: [
      { key: 'syllabusMonId', label: 'Syllabus môn học', format: 'syllabusMon' },
      { key: 'loai', label: 'Loại điều kiện' },
      { key: 'noiDung', label: 'Nội dung' },
      { key: 'thuTu', label: 'Thứ tự', format: 'number' },
    ],
    fields: [
      field('syllabusMonId', 'Syllabus môn học', 'select', { optionKey: 'syllabusMon', required: true }),
      field('loai', 'Loại điều kiện', 'select', { optionKey: 'dieuKienMonLoai', required: true }),
      field('noiDung', 'Nội dung', 'textarea', { wide: true, required: true }),
      field('thuTu', 'Thứ tự', 'number'),
    ],
    create: createDieuKienMonHoc,
    update: updateDieuKienMonHoc,
    remove: deleteDieuKienMonHoc,
  },
  'quy-doi-diem': {
    title: 'Quy đổi điểm',
    subtitle: 'Thiết lập ngưỡng quy đổi điểm và kết quả đạt/không đạt cho từng môn trong chương trình.',
    dataKey: 'scoreConversions',
    scope: 'course',
    searchFields: ['ketQua', 'congThuc', 'ghiChu'],
    columns: [
      { key: 'chuongTrinhMonId', label: 'Môn trong CT', format: 'course' },
      { key: 'nguongTu', label: 'Ngưỡng từ', format: 'number' },
      { key: 'nguongDen', label: 'Ngưỡng đến', format: 'number' },
      { key: 'diemQuyDoi', label: 'Điểm quy đổi', format: 'number' },
      { key: 'ketQua', label: 'Kết quả' },
    ],
    fields: [
      field('chuongTrinhMonId', 'Môn trong chương trình', 'select', { optionKey: 'course', required: true }),
      field('nguongTu', 'Ngưỡng từ', 'number'),
      field('nguongDen', 'Ngưỡng đến', 'number'),
      field('diemQuyDoi', 'Điểm quy đổi', 'number'),
      field('ketQua', 'Kết quả', 'select', { optionKey: 'ketQuaQuyDoi' }),
      field('congThuc', 'Công thức', 'textarea', { wide: true }),
      field('ghiChu', 'Ghi chú', 'textarea', { wide: true }),
    ],
    create: createQuyDoiDiem,
    update: updateQuyDoiDiem,
    remove: deleteQuyDoiDiem,
  },
};
