export const CHUONG_TRINH_COLUMNS = {
  nganh: [
    { key: 'maNganh', label: 'Mã ngành' },
    { key: 'tenNganh', label: 'Tên ngành' },
    { key: 'moTa', label: 'Mô tả', truncate: true },
  ],
  'trinh-do-dao-tao': [
    { key: 'maTrinhDo', label: 'Mã trình độ' },
    { key: 'tenTrinhDo', label: 'Tên trình độ' },
    { key: 'moTa', label: 'Mô tả', truncate: true },
  ],
  'loai-chuong-trinh': [
    { key: 'maLoai', label: 'Mã loại' },
    { key: 'tenLoai', label: 'Tên loại' },
    { key: 'soThang', label: 'Số tháng', align: 'right' },
    { key: 'soKy', label: 'Số kỳ', align: 'right' },
    { key: 'moTa', label: 'Mô tả', truncate: true },
  ],
  'chuong-trinh': [
    { key: 'maChuongTrinh', label: 'Mã CT' },
    { key: 'tenChuongTrinh', label: 'Tên chương trình', truncate: true },
    { key: 'nganhId', label: 'Ngành' },
    { key: 'trinhDoId', label: 'Trình độ' },
    { key: 'loaiChuongTrinhId', label: 'Loại CT' },
    { key: 'thoiGianDaoTao', label: 'Thời gian' },
  ],
  'chuong-trinh-version': [
    { key: 'maVersion', label: 'Mã version' },
    { key: 'tenVersion', label: 'Tên version', truncate: true },
    { key: 'soQuyetDinh', label: 'Số QĐ' },
    { key: 'ngayQuyetDinh', label: 'Ngày QĐ', type: 'date' },
    { key: 'tongTinChi', label: 'Tín chỉ', align: 'right' },
    { key: 'tongSoGio', label: 'Tổng giờ', align: 'right' },
    { key: 'laHienHanh', label: 'Hiện hành', type: 'boolean' },
  ],
  'syllabus-chuong-trinh': [
    { key: 'chuongTrinhVersionId', label: 'Version' },
    { key: 'moTaTongQuan', label: 'Mô tả tổng quan', truncate: true },
    { key: 'mucDich', label: 'Mục đích', truncate: true },
    { key: 'phuongPhapDaoTao', label: 'Phương pháp', truncate: true },
  ],
  'muc-tieu-chuong-trinh': [
    { key: 'loai', label: 'Loại' },
    { key: 'noiDung', label: 'Nội dung', truncate: true },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
  'nang-luc-dau-ra': [
    { key: 'ma', label: 'Mã' },
    { key: 'noiDung', label: 'Nội dung', truncate: true },
    { key: 'loai', label: 'Loại' },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
  'vi-tri-viec-lam': [
    { key: 'ten', label: 'Tên vị trí' },
    { key: 'moTa', label: 'Mô tả', truncate: true },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
  'khung-ky': [
    { key: 'loaiChuongTrinhId', label: 'Loại CT' },
    { key: 'maKy', label: 'Mã kỳ' },
    { key: 'tenKy', label: 'Tên kỳ' },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
  'nhom-kien-thuc': [
    { key: 'ma', label: 'Mã nhóm' },
    { key: 'ten', label: 'Tên nhóm', truncate: true },
    { key: 'loaiNhom', label: 'Loại nhóm' },
    { key: 'tongTinChi', label: 'Tín chỉ', align: 'right' },
    { key: 'tongSoGio', label: 'Tổng giờ', align: 'right' },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
  'mon-hoc': [
    { key: 'maMon', label: 'Mã môn' },
    { key: 'tenMon', label: 'Tên môn', truncate: true },
    { key: 'moTa', label: 'Mô tả', truncate: true },
  ],
  'chuong-trinh-mon': [
    { key: 'maMonTrongCt', label: 'Mã môn CT' },
    { key: 'monHocId', label: 'Môn học' },
    { key: 'khungKyId', label: 'Kỳ' },
    { key: 'nhomKienThucId', label: 'Nhóm' },
    { key: 'loai', label: 'Loại' },
    { key: 'loaiHocPhan', label: 'Học phần' },
    { key: 'soTinChi', label: 'TC', align: 'right' },
    { key: 'tongGio', label: 'Giờ', align: 'right' },
    { key: 'batBuoc', label: 'Bắt buộc', type: 'boolean' },
  ],
  'mon-tien-quyet': [
    { key: 'monId', label: 'Môn chính' },
    { key: 'monDieuKienId', label: 'Môn điều kiện' },
    { key: 'loai', label: 'Loại' },
    { key: 'ghiChu', label: 'Ghi chú', truncate: true },
  ],
  'nhom-tu-chon': [
    { key: 'ten', label: 'Tên nhóm' },
    { key: 'soMonChon', label: 'Số môn chọn', align: 'right' },
    { key: 'soTinChiCanDat', label: 'TC cần đạt', align: 'right' },
    { key: 'ghiChu', label: 'Ghi chú', truncate: true },
  ],
  'syllabus-mon-hoc': [
    { key: 'chuongTrinhMonId', label: 'Môn CT' },
    { key: 'viTri', label: 'Vị trí', truncate: true },
    { key: 'tinhChat', label: 'Tính chất' },
    { key: 'diemDatToiThieu', label: 'Điểm đạt', align: 'right' },
    { key: 'donViDiem', label: 'Đơn vị' },
    { key: 'batBuocDuThi', label: 'Dự thi', type: 'boolean' },
  ],
  'syllabus-chuong-bai': [
    { key: 'ten', label: 'Tên chương/bài', truncate: true },
    { key: 'tongGio', label: 'Tổng giờ', align: 'right' },
    { key: 'gioLyThuyet', label: 'LT', align: 'right' },
    { key: 'gioThucHanh', label: 'TH', align: 'right' },
    { key: 'gioKiemTra', label: 'KT', align: 'right' },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
  'syllabus-tai-lieu': [
    { key: 'ten', label: 'Tên tài liệu', truncate: true },
    { key: 'tacGia', label: 'Tác giả' },
    { key: 'namXuatBan', label: 'Năm XB', align: 'right' },
    { key: 'nhaXuatBan', label: 'NXB' },
    { key: 'loai', label: 'Loại' },
  ],
  'dieu-kien-mon-hoc': [
    { key: 'loai', label: 'Loại' },
    { key: 'noiDung', label: 'Nội dung', truncate: true },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
  'quy-doi-diem': [
    { key: 'nguongTu', label: 'Từ', align: 'right' },
    { key: 'nguongDen', label: 'Đến', align: 'right' },
    { key: 'diemQuyDoi', label: 'Điểm QĐ', align: 'right' },
    { key: 'ketQua', label: 'Kết quả' },
    { key: 'ghiChu', label: 'Ghi chú', truncate: true },
  ],
  'dieu-kien-tot-nghiep': [
    { key: 'noiDung', label: 'Nội dung', truncate: true },
    { key: 'thuTu', label: 'Thứ tự', align: 'right' },
  ],
};
