<template>
  <section class="lms-page">
    <div class="page-head"><div><h1>Bài tập online</h1><p>Template bài tập lấy câu hỏi version đã duyệt hoặc sinh đề theo ma trận.</p></div><RouterLink :to="{ name:'Lms.BaiTapOnlineThem' }" class="lms-btn primary">+ Tạo bài tập</RouterLink></div>
    <div class="filter-card"><input v-model.trim="keyword" class="fi" placeholder="Tìm tiêu đề, môn học..."/><select v-model="trangThai" class="fi"><option value="">Tất cả trạng thái</option><option v-for="(label,key) in TRANG_THAI_BAI_TAP_ONLINE" :key="key" :value="key">{{ label }}</option></select><button class="lms-btn" @click="taiDuLieu">Tải lại</button></div>
    <div class="table-card"><table><thead><tr><th>Bài tập</th><th>Môn học</th><th>Loại</th><th>Cấu hình</th><th>Câu hỏi</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr v-if="dangTai"><td colspan="7" class="empty">Đang tải...</td></tr><tr v-else-if="!dsLoc.length"><td colspan="7" class="empty">Chưa có bài tập online.</td></tr><tr v-for="b in dsLoc" :key="b.id"><td><b>{{ b.tieuDe }}</b><br/><small>ID {{ b.id }} · {{ b.moTa || 'Không mô tả' }}</small></td><td>{{ b.tenMonHoc }}<br/><small>{{ b.maMonHoc }}</small></td><td>{{ LOAI_BAI[b.loaiBai] || b.loaiBai }}</td><td><span class="pill" v-if="b.sinhDeTuDong">Ma trận #{{ b.maTranDeId }}</span><span class="pill" v-if="b.tronCauHoi">Trộn câu</span><span class="pill" v-if="b.tronDapAn">Trộn đáp án</span></td><td><b>{{ b.soCauHoi || 0 }}</b><br/><small>Tổng điểm {{ b.tongDiem }}</small></td><td><LmsBadge :value="b.trangThai" :map="TRANG_THAI_BAI_TAP_ONLINE" :color-fn="badgeClass" /></td><td class="actions"><RouterLink :to="{name:'Lms.BaiTapOnlineSua',params:{id:b.id}}" class="act">Sửa</RouterLink><RouterLink :to="{name:'Lms.GiaoBai',query:{baiTapOnlineId:b.id}}" class="act ok">Giao lớp</RouterLink><button class="act" @click="saoChep(b)">Sao chép</button><button class="act danger" @click="xoa(b)">Xóa</button></td></tr></tbody></table></div>
  </section>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import LmsBadge from '../components/LmsBadge.vue'
import { baiTapOnlineService } from '../services/lmsService'
import { LOAI_BAI, TRANG_THAI_BAI_TAP_ONLINE, badgeClass } from '../services/lmsEnum'
const dangTai=ref(false), items=ref([]), keyword=ref(''), trangThai=ref('')
const dsLoc=computed(()=>{ const kw=keyword.value.toLowerCase(); return items.value.filter(b=>(!kw||`${b.tieuDe} ${b.tenMonHoc}`.toLowerCase().includes(kw))&&(!trangThai.value||b.trangThai===trangThai.value)) })
async function taiDuLieu(){ dangTai.value=true; try{ items.value=(await baiTapOnlineService.layDanhSach()).content } finally{ dangTai.value=false } }
async function saoChep(b){ await baiTapOnlineService.saoChep(b.id); await taiDuLieu() }
async function xoa(b){ if(confirm('Xóa bài tập online này?')){ await baiTapOnlineService.xoa(b.id); await taiDuLieu() } }
onMounted(taiDuLieu)
</script>
<style scoped>.lms-page{font-family:Roboto,Arial,sans-serif}.page-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.page-head h1{margin:0;font-size:24px;font-weight:800}.page-head p{margin:4px 0;color:#64748b}.filter-card,.table-card{background:#fff;border:1px solid #e2e8f0;border-radius:14px}.filter-card{display:grid;grid-template-columns:1fr 220px auto;gap:10px;padding:14px;margin-bottom:14px}.fi{height:38px;border:1px solid #dbe3ef;border-radius:10px;padding:0 12px}.table-card{overflow:auto}table{width:100%;border-collapse:collapse}th{background:#f8fafc;color:#475569;text-align:left;font-size:12px;text-transform:uppercase;padding:12px}td{border-top:1px solid #eef2f7;padding:12px;font-size:13px;vertical-align:top}.empty{text-align:center;padding:32px!important;color:#94a3b8}.lms-btn,.act{display:inline-flex;border:1px solid #dbe3ef;border-radius:10px;background:#fff;padding:8px 12px;font-weight:700;color:#334155;text-decoration:none;cursor:pointer}.lms-btn.primary{background:#1d4ed8;color:#fff;border-color:#1d4ed8}.act{padding:6px 10px;margin:2px}.act.ok{color:#15803d}.act.danger{color:#b91c1c}.pill{display:inline-block;background:#eff6ff;color:#1d4ed8;border-radius:999px;padding:3px 8px;font-size:12px;margin:2px}.badge-gray{background:#f1f5f9;color:#64748b}.badge-green{background:#dcfce7;color:#15803d}.badge-orange{background:#fff7ed;color:#c2410c}.badge-red{background:#fee2e2;color:#b91c1c}@media(max-width:800px){.filter-card{grid-template-columns:1fr}.page-head{flex-direction:column}}</style>
